require: rubocop-rails
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'libs/**/*'
    - 'vendor/**/*'
    - 'spec/factories/**/*'
    - 'tmp/**/*'
  NewCops: enable

Rails:
  Enabled: true