version: "3.8"

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rdebug-ide --host 0.0.0.0 --port 9000 -- bin/rails s -p 3000 -b 0.0.0.0"
    ports:
      - 9000:9000